version: '3'

volumes:
  postgres_volume:

services:
  pg:
    image: postgres:14-alpine3.17
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"

    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/val/lib/postgre/data

  migrator:
    build:
      context: postgre
      dockerfile: migration.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: db